// <auto-generated />
namespace LearnerProject.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class mig_teacher_table_update : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(mig_teacher_table_update));
        
        string IMigrationMetadata.Id
        {
            get { return "202404222319181_mig_teacher_table_update"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
